#!/bin/sh
# Regenerates web/src/styles/tokens.base.css from the jcode-ui scoped tokens.
#
# The web app's own chrome (sidebar, header, xterm, …) themes via the legacy
# unprefixed names (--color-*, --font-*, …) at :root — jcode-ui ≥0.2 no longer
# leaks those. This derives the legacy base by un-scoping the library tokens.
# jcode-ui components pick the same values back up through jcode-ui/compat.css.
set -e
cd "$(dirname "$0")/.."
src=packages/jcode-ui/src/styles/tokens.css
out=web/src/styles/tokens.base.css
{
  echo "/* Code generated by script/sync-web-base-tokens.sh; DO NOT EDIT."
  echo " * Legacy-name base tokens for the web app chrome (:root/.dark),"
  echo " * derived from $src. */"
  # 1. un-scope selectors  2. strip the --jcode- prefix everywhere
  sed -e 's/^\.dark \[data-jcode-ui\],$/.dark {/' \
      -e '/^\[data-jcode-ui\]\.dark {$/d' \
      -e 's/^\[data-jcode-ui\] \.hljs/.hljs/' \
      -e 's/^\[data-jcode-ui\] {$/:root {/' \
      -e 's/--jcode-/--/g' \
      "$src"
} > "$out"
echo "wrote $out"
