import './legal.css'

export default function PrivacyPage() {
  return (
    <main className="legal-page">
      <div className="container legal">
        <span className="mono-label">Privacy</span>
        <h1>jcode Browser Bridge — Privacy Policy</h1>
        <p className="legal-updated">Last updated: July 4, 2026</p>

        <p>
          <strong>jcode Browser Bridge</strong> is the optional Chrome/Edge extension for{' '}
          <a href="https://www.j-code.net">jcode</a>, an open-source AI coding agent. The
          extension lets a copy of jcode running <strong>on your own machine</strong> see and
          operate your browser through the Chrome DevTools Protocol. This policy explains exactly
          what the extension touches and where that data goes.
        </p>

        <div className="legal-note">
          <p>
            <strong>The short version:</strong> the extension only ever talks to a jcode server on
            your own computer over a local loopback connection (<code>127.0.0.1</code> /{' '}
            <code>localhost</code>). It sends nothing to us or to any third-party server. There is
            no analytics, no tracking, and no advertising.
          </p>
        </div>

        <h2>What the extension accesses, and why</h2>
        <ul>
          <li>
            <strong>Debugger (CDP)</strong> — to relay commands and events for the tabs jcode
            controls. Chrome shows its &ldquo;{`is being debugged`}&rdquo; banner the whole time a
            tab is attached; detaching (or clicking <em>Cancel</em> on that banner) hands control
            back and jcode stops.
          </li>
          <li>
            <strong>Tabs &amp; tab groups</strong> — to open, switch and group the tabs under agent
            control. Controlled tabs are placed in a visible &ldquo;jcode 🔎&rdquo; tab group so you
            can always see which tabs are being driven.
          </li>
          <li>
            <strong>Native messaging</strong> — to discover the jcode app running on your machine
            (even on a dynamic local port) and obtain its local server URL and a pairing token.
          </li>
          <li>
            <strong>Storage</strong> — to keep the local server URL and pairing token in{' '}
            <code>chrome.storage.local</code> so you only have to connect once.
          </li>
          <li>
            <strong>Host access limited to loopback</strong> — the extension&rsquo;s host
            permissions are restricted to <code>http://127.0.0.1/*</code> and{' '}
            <code>http://localhost/*</code>. It can only reach a jcode server on your own machine.
          </li>
        </ul>

        <h2>Data it handles and where it goes</h2>
        <ul>
          <li>
            <strong>Pairing token &amp; server URL</strong> — generated by your local jcode app and
            stored in <code>chrome.storage.local</code>. Used only to open the local WebSocket
            connection to that app. Never transmitted anywhere else.
          </li>
          <li>
            <strong>Page content, DOM and screenshots</strong> — when the agent inspects or acts on
            a page, that content is relayed between the browser tab and your local jcode app. The
            extension does not store it and does not send it to any remote or third-party server.
          </li>
        </ul>

        <div className="legal-note">
          <p>
            <strong>One honest caveat.</strong> The jcode <em>application</em> on your machine is a
            &ldquo;bring your own model&rdquo; tool: to do the work you ask, it may send the page
            content it reads to the AI model provider <em>you</em> have configured. That
            transmission is performed by the jcode app under your control and your provider&rsquo;s
            terms — not by this extension. The extension itself only moves data between your browser
            and your local jcode app.
          </p>
        </div>

        <h2>What the extension does not do</h2>
        <ul>
          <li>It does not send any data to servers operated by us.</li>
          <li>It does not include analytics, telemetry, trackers, or advertising.</li>
          <li>It does not sell or share your data with anyone.</li>
          <li>It does not connect to any host other than your local jcode server.</li>
        </ul>

        <h2>Retention and your control</h2>
        <p>
          The pairing token and server URL persist in <code>chrome.storage.local</code> until you
          remove them. Use <strong>Disconnect</strong> in the extension popup to revoke the token
          and detach every controlled tab, or remove the extension to erase all of its stored data.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about this policy or the extension can be raised on our{' '}
          <a href="https://github.com/cnjack/jcode/issues" target="_blank" rel="noreferrer">
            GitHub issue tracker
          </a>
          . The extension&rsquo;s source is part of the open-source jcode project at{' '}
          <a href="https://github.com/cnjack/jcode" target="_blank" rel="noreferrer">
            github.com/cnjack/jcode
          </a>
          .
        </p>

        <h2>Changes to this policy</h2>
        <p>
          If the extension&rsquo;s data handling changes, this page will be updated and the
          &ldquo;Last updated&rdquo; date above will change accordingly.
        </p>
      </div>
    </main>
  )
}
